name: pe_exam_package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
   branches: [ "master" , "development", "staging"]
  pull_request:
   branches: [ "master" , "development", "staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  #schedule:
  #- cron: "*/10 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: runner-1
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.5

      - name: Install pytest
        run: pip install pytest

      - name: run pytest
        run: pytest
